language: ruby
rvm:
  - 2.0.0
  - 2.2.0
  - 2.2.3
  - 2.3.0
  - 2.3.1
  - jruby
script:
  - bundle install
  - gem build wowapi.gemspec
notifications:
  email: true
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#wowapi"
